all:
	mkdir ./results
	mkdir ./content
	mkdir ./content/models/
	mkdir ./content/results/
	mkdir ./content/dataset/

fclean:
	rm -rf ./content
	rm -rf ./results

clean:
	rm -rf ./content/models/*
	rm -rf ./content/results/*
	rm -rf ./content/dataset/*
	rm -rf ./results/*.xlsx



