all:
	mkdir ./content
	mkdir ./content/models/
	mkdir ./content/results/
	mkdir ./content/dataset/


fclean: clean
	rm -rf ./content

clean:
	rm -rf ./content/models/*
	rm -rf ./content/results/*
	rm -rf ./content/dataset/*
	rm -rf ./*.xlsx
